### ISSUE TITLE
I meet some error ,who can help me,please?

### ISSUE THREAD

**Issue by StevenJames1** [matthewearl/deep-anpr#14]
My tensorflow is version of 0.8,and cudnn is v4.0 and cuda is  7.5, when I run train.py ,there is an error occur

![2016](https://cloud.githubusercontent.com/assets/22994859/19635005/ab6f48c4-99f1-11e6-87ac-89abd18ec34c.PNG)

**Comment by ChadTaljaardt** [comment]
can you paste the terminal output rather than have a image of it?

**Comment by StevenJames1** [comment]
The terminal output information as follows, thanks for your trouble

maheng@master:~/code/deep-anpr-master$ python train.py 
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:900] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: GeForce GTX 750 Ti
major: 5 minor: 0 memoryClockRate (GHz) 1.189
pciBusID 0000:01:00.0
Total memory: 2.00GiB
Free memory: 1.75GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:755] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 750 Ti, pci bus id: 0000:01:00.0)
E tensorflow/stream_executor/cuda/cuda_dnn.cc:289] could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
E tensorflow/stream_executor/cuda/cuda_dnn.cc:278] could not destroy cudnn handle: CUDNN_STATUS_BAD_PARAM
W tensorflow/stream_executor/stream.cc:301] attempting to perform DNN operation using StreamExecutor without DNN support
Traceback (most recent call last):
  File "train.py", line 265, in <module>
    initial_weights=initial_weights)
  File "train.py", line 238, in train
    do_batch()
  File "train.py", line 221, in do_batch
    feed_dict={x: batch_xs, y_: batch_ys})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 340, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 564, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 637, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 659, in _do_call
    e.code)
tensorflow.python.framework.errors.InternalError: cuDNN launch failure : input shape([50,1,64,128]) filter shape([5,5,1,48])
     [[Node: Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](ExpandDims, Variable/read)]]
Caused by op u'Conv2D', defined at:
  File "train.py", line 265, in <module>
    initial_weights=initial_weights)
  File "train.py", line 169, in train
    x, y, params = model.get_training_model()
  File "/home/maheng/code/deep-anpr-master/model.py", line 112, in get_training_model
    x, conv_layer, conv_vars = convolutional_layers()
  File "/home/maheng/code/deep-anpr-master/model.py", line 80, in convolutional_layers
    h_conv1 = tf.nn.relu(conv2d(x_expanded, W_conv1) + b_conv1)
  File "/home/maheng/code/deep-anpr-master/model.py", line 56, in conv2d
    padding=padding)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 295, in conv2d
    data_format=data_format, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 655, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2154, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1154, in __init__
    self._traceback = _extract_stack()

**Comment by ChadTaljaardt** [comment]
looks somewhat related to this 

https://github.com/tensorflow/tensorflow/issues/2264

**Comment by ChadTaljaardt** [comment]
I used Ubuntu 16.10 and Cudnn 5.1.5 and CUDA 8.0

**Comment by ChadTaljaardt** [comment]
Any Update?

**Comment by hungpt297** [comment]
Work for me.
Ubuntu 16.10, Tesla K40c, Cuda 8.0, Cudnn 5.1, Tensorflow 0.12, Opencv 2.4.9

**Comment by suchetasu** [comment]
I am also having the same error. Can anyone help to resolve it?

**Comment by ChadTaljaardt** [comment]
@suchetasu I had this issue a little while ago, what tensor flow version are you using?

**Comment by guddulrk** [comment]
I have this issue, can anyone help?

Can't pickle local object 'mpgen.<locals>.main'

**Comment by ChadTaljaardt** [comment]
@guddulrk What tensorflow version are you using?

**Comment by chingjunehao** [comment]
Traceback (most recent call last):
  File "./detect.py", line 183, in <module>
    f = np.loadtxt("weights.npz")
  File "C:\Users\User\Anaconda3\envs\py35\lib\site-packages\numpy\lib\npyio.py", line 1024, in loadtxt
    items = [conv(val) for (conv, val) in zip(converters, vals)]
  File "C:\Users\User\Anaconda3\envs\py35\lib\site-packages\numpy\lib\npyio.py", line 1024, in <listcomp>
    items = [conv(val) for (conv, val) in zip(converters, vals)]
  File "C:\Users\User\Anaconda3\envs\py35\lib\site-packages\numpy\lib\npyio.py", line 725, in floatconv
    return float(x)
ValueError: could not convert string to float: b'PF\x05\x06\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

I met this error in windows, is there anyone can help with this?

**Comment by ChadTaljaardt** [comment]
@chingjunehao That's a different issue to everyone else, please open a new issue for it.

**Comment by chingjunehao** [comment]
@ChadTaljaardt okay, sorry. I have opened and thanks for reminding! Can you help me with it?

**Comment by ChadTaljaardt** [comment]
@chingjunehao your issue is that the value is not a string its bytecode. You need to make sure your file is valid im assuming and not corrupted. 

I might be wrong but thats my guess.

**Comment by ChadTaljaardt** [comment]
@StevenJames1 If you dont have this issue anymore, please can you close it.
