### ISSUE TITLE
Error running ./train.py

### ISSUE THREAD

**Issue by pentateu** [matthewearl/deep-anpr#15]
Hi,

I'm getting this error while trying to execute "train.py", I had a look at the code. but it was not obvious to me the root cause.
This happens the second time 'read_batches' is invoked. 

B120 60.00% 60.00% loss: 1295.7512207 (digits: 1057.39453125, presence: 238.356689453) |X X   XX    X   X X  X X XX XXX  X        XX  XX X|
time for 60 batches 175.30300498
Process Process-1:
Traceback (most recent call last):
  File "/Users/rafael/anaconda2/envs/tensorflow/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/rafael/anaconda2/envs/tensorflow/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./train.py", line 92, in main
    for item in f(*args, **kwargs):
  File "./train.py", line 122, in read_batches
    yield unzip(gen_vecs())
  File "./train.py", line 72, in unzip
    xs, ys = zip(*b)
TypeError: zip() argument after * must be a sequence, not generator

**Comment by sapeyes** [comment]
I have similar problem.. 

Traceback (most recent call last):
  File "<stdin>", line 277, in <module>
  File "<stdin>", line 248, in train
  File "<stdin>", line 106, in wrapped
  File "C:\Users\D-IPS-TERM\AppData\Local\Programs\Python\Python35\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\D-IPS-TERM\AppData\Local\Programs\Python\Python35\lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\D-IPS-TERM\AppData\Local\Programs\Python\Python35\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "C:\Users\D-IPS-TERM\AppData\Local\Programs\Python\Python35\lib\multiprocessing\popen_spawn_win32.py", line 66, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\D-IPS-TERM\AppData\Local\Programs\Python\Python35\lib\multiprocessing\reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'mpgen.<locals>.main'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\D-IPS-TERM\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\D-IPS-TERM\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 115, in _main
    prepare(preparation_data)
  File "C:\Users\D-IPS-TERM\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 226, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\D-IPS-TERM\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 278, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\D-IPS-TERM\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 252, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "C:\Users\D-IPS-TERM\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 222, in _get_code_from_file
    with open(fname, "rb") as f:
OSError: [Errno 22] Invalid argument: 'D:\\deep-anpr\\<stdin>'
shell returned 1
Hit any key to close this window...

**Comment by sapeyes** [comment]
I just deleted multicore processing part of mpgen for reading images using multiple processors. It is running now but slowly. Just comment @mpeg as below. That's it to avoid this error. 

#@mpgen
def read_batches(batch_size):
