### ISSUE TITLE
ValueError: Cannot feed value of shape (2048,) for Tensor u'Variable_6:0', which has shape '(32768, 2048)'

### ISSUE THREAD

**Issue by Pasquinell** [matthewearl/deep-anpr#21]
This error shows when I run 
`./detect.py test/00000361_PI50NFZ_1.png weights.npz out.jpg` : 

````
libdc1394 error: Failed to initialize libdc1394
Traceback (most recent call last):
  File "./detect.py", line 178, in <module>
    detect(im_gray, param_vals)):
  File "./detect.py", line 152, in post_process
    groups = _group_overlapping_rectangles(matches)
  File "./detect.py", line 125, in _group_overlapping_rectangles
    matches = list(matches)
  File "./detect.py", line 87, in detect
    y_vals.append(sess.run(y, feed_dict=feed_dict))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 943, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (2048,) for Tensor u'Variable_6:0', which has shape '(32768, 2048)'

```


I read that this error `libdc1394 error: Failed to initialize libdc1394` is not a problem. The main error is a shape problem that I cant fix yet. I have tryed loading several images (also one taken by me). Can anyone help me?

**Comment by guddulrk** [comment]
I am getting following error:
pt1 = tuple(reversed(map(int, pt1)))

TypeError: argument to reversed() must be a sequence

any help please?

**Comment by jesiws** [comment]
I met the same error...you can download a trained model which has been provided in this issue https://github.com/matthewearl/deep-anpr/issues/12 and you will find it works out fine. 

I think it might be caused by an incomplete model. Try to train a new model may be the solution.
