### ISSUE TITLE
Index Error while running train.py 

### ISSUE THREAD

**Issue by ZackTack** [matthewearl/deep-anpr#26]
Hi, 
  I am at the phase of training the network. I ran the extractbgs.py and gen.py with no problem. After that, I got backgrounds and 1000 test samples. However, I could not run train.py with the following error as the next step.
  I think it doesn't read those filenames correctly but I don't know how to fix it. Anyone can help?

Traceback (most recent call last):
  File "C:\Users\Guest1\Documents\Python Projects\deep-anpr-master\train.py", line 265, in <module>
    initial_weights=initial_weights)
  File "C:\Users\Guest1\Documents\Python Projects\deep-anpr-master\train.py", line 232, in train
    test_xs, test_ys = unzip(list(read_data("test/*.png"))[:50])
  File "C:\Users\Guest1\Documents\Python Projects\deep-anpr-master\train.py", line 66, in read_data
    code = fname.split('/')[1][9:16]
IndexError: list index out of range

**Comment by ZackTack** [comment]
I managed to solve this problem with double slash not single by debugging.

**Comment by sourabh2k15** [comment]
yeah for windows it has to be changed
