### ISSUE TITLE
Error running ./extractbgs.py SUN397.tar.gz

### ISSUE THREAD

**Issue by Maya1994** [matthewearl/deep-anpr#33]
Hello,
I'm getting this error while trying to execute ./extractbgs.py SUN397.tar.gz !

Traceback (most recent call last):
  File "./extractbgs.py", line 97, in <module>
    extract_backgrounds(sys.argv[1])
  File "./extractbgs.py", line 75, in extract_backgrounds
    im = im_from_file(f)
  File "./extractbgs.py", line 46, in im_from_file
    return cv2.imdecode(a, cv2.CV_LOAD_IMAGE_GRAYSCALE)
AttributeError: 'module' object has no attribute 'CV_LOAD_IMAGE_GRAYSCALE'

can anyone help me please ! 
Thanks,

**Comment by rphly** [comment]
Change: `return cv2.imdecode(a, cv2.CV_LOAD_IMAGE_GRAYSCALE)`
to: `return cv2.imdecode(a, 0)`

The former has been deprecated in the newer version of OpenCV! :)

**Comment by ghost** [comment]
You can change also CV_LOAD_IMAGE_GRAYSCALE by IMREAD_GRAYSCALE on all yours files :-)

**Comment by Maya1994** [comment]
thanks so much  :D it works now

**Comment by Maya1994** [comment]
I'm trying now to run train.py :/ but i got this error !!! 
can u help me again ! 
i ' m beginner in python and deep learning !

File "./train.py", line 276, in <module>
    initial_weights=initial_weights)
  File "./train.py", line 238, in train
    sess.run(init)

**Comment by ghost** [comment]
It's maybe that ? I don't really know but maybe so try it ! :-) 
https://github.com/matthewearl/deep-anpr/pull/23/files

**Comment by ghost** [comment]
So ?

**Comment by Maya1994** [comment]
thanks novsub for ur response , but it's not that i have already change the digits_loss  and the presence_loss :/

**Comment by susancurry** [comment]
I would like to ask you how to make extractbgs.py SUN397.tar.gz implementation

**Comment by susancurry** [comment]
File "./extractbgs.py", line 97, in 
extract_backgrounds(sys.argv[1])


This line of the error is to use what method to solve

**Comment by susancurry** [comment]
File "extractbgs.py", line 87
    fname = "bgs/{:08d}.jpg".format(index)
這個bug要怎麼解決~~

**Comment by cayman1021** [comment]
Hello sunsancurry,
Simply run "extractbgs.py SUN397.tar.gz" under Command Prompt mode since my environment is Windows 10.
It will extract several thousands of JPG files from it.
I didn't encounter any bug while extracting those files.
