### ISSUE TITLE
Error running train.py

### ISSUE THREAD

**Issue by Maya1994** [matthewearl/deep-anpr#34]
I'm trying now to run train.py :/ but i got this error !!!
can u help me again !

File "./train.py", line 276, in 
initial_weights=initial_weights)
File "./train.py", line 238, in train
sess.run(init)

**Comment by rphly** [comment]
Can you post the full error? There is no context.

**Comment by sourabh2k15** [comment]
If you are running it on windows, change "/" to "\" in the function where it reads path of training files 
also try commenting @mpgen line , which uses multiple processes to make it faster 

lastly, delete any weights.npz already in the folder 
Do post the full error output so we can help better

**Comment by Maya1994** [comment]
thanks for the reply , actually i'm on ubuntu 14.04
here is the full error : 
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "./train.py", line 276, in <module>
    initial_weights=initial_weights)
  File "./train.py", line 238, in train
    sess.run(init)
  File "/home/nahla/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/nahla/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 952, in _run
    fetch_handler = _FetchHandler(self._graph, fetches, feed_dict_string)
  File "/home/nahla/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 408, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)
  File "/home/nahla/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 238, in for_fetch
    return _ElementFetchMapper(fetches, contraction_fn)
  File "/home/nahla/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 271, in __init__
    % (fetch, type(fetch), str(e)))
TypeError: Fetch argument <function global_variables_initializer at 0x7f9a890cc410> has invalid type <type 'function'>, must be a string or Tensor. (Can not convert a function into a Tensor or Operation.)
