### ISSUE TITLE
Can  not run the detect.py?

### ISSUE THREAD

**Issue by SunAriesCN** [matthewearl/deep-anpr#4]
"~/deep-anpr$ ./detect.py Proton_Saga_EV_at_the_RAC_Future_Car_Challenge_2011,_U.K.jpg weights.npz out.jpg
Traceback (most recent call last):
  File "./detect.py", line 186, in <module>
    detect(im_gray, param_vals)):
  File "./detect.py", line 160, in post_process
    groups = _group_overlapping_rectangles(matches)
  File "./detect.py", line 131, in _group_overlapping_rectangles
    matches = list(matches)
  File "./detect.py", line 91, in detect
    feed_dict = {x: numpy.stack([scaled_im])}
AttributeError: 'module' object has no attribute 'stack'"
I don't know why my numpy have no stack function?

**Comment by SunAriesCN** [comment]
I just found that numpy.max have no 'flatten' function, how can you run that script?

**Comment by SunAriesCN** [comment]
OK, I may work it out by enter following instruction: 
$sudo apt-get install python-pip
$sudo pip install --upgrade numpy
