### ISSUE TITLE
Train.py on Windows

### ISSUE THREAD

**Issue by cyrsis** [matthewearl/deep-anpr#40]
"C:\Program Files\Anaconda3\envs\tensorflow-gpu\python.exe" D:/deep-anpr/train.py
WARNING:tensorflow:From D:/deep-anpr/train.py:184: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
2017-05-11 14:18:19.713921: W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE instructions, but these are available on your machine and could speed up CPU computations.
2017-05-11 14:18:19.714346: W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE2 instructions, but these are available on your machine and could speed up CPU computations.
2017-05-11 14:18:19.714885: W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
2017-05-11 14:18:19.715274: W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-05-11 14:18:19.715641: W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-05-11 14:18:19.715887: W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-05-11 14:18:20.135785: I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:887] Found device 0 with properties: 
name: GeForce GTX 950
major: 5 minor: 2 memoryClockRate (GHz) 1.266
pciBusID 0000:04:00.0
Total memory: 2.00GiB
Free memory: 1.65GiB
2017-05-11 14:18:20.136117: I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:908] DMA: 0 
2017-05-11 14:18:20.136271: I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:918] 0:   Y 
2017-05-11 14:18:20.136449: I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:977] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 950, pci bus id: 0000:04:00.0)
Traceback (most recent call last):
  File "D:/deep-anpr/train.py", line 266, in <module>
    initial_weights=initial_weights)
  File "D:/deep-anpr/train.py", line 232, in train
    test_xs, test_ys = unzip(list(read_data("test/*.png"))[:50])
  File "D:/deep-anpr/train.py", line 65, in read_data
    code = fname.split("D:\deep-anpr\test")[1][9:16]
IndexError: list index out of range

I try out different setting and a few run, still cannt figure out the problem yet

Can you take a look?

**Comment by stanlee321** [comment]
I get the same problem, change the lines corresponding to code = fname.split("D:\deep-anpr\test")[1][9:16]
to code = fname.split("D:\deep-anpr\test")[0][9:16] ........ from '0' first value of the list.

**Comment by cayman1021** [comment]
I don't need to modify the index of the array.
Simply modify the following two lines:
"code = fname.split("\\")[1][9:16]"
"p = fname.split("\\")[1][17] == '1'"
, since I'm running it under Windows 10.

But now I got another problem "EOFError: Ran out of input". :(
