### ISSUE TITLE
Second branch

### ISSUE THREAD

**Issue by ghost** [matthewearl/deep-anpr#41]
Does anyone have this problem about the second branch in the train.py?

Traceback (most recent call last):
  File "./train.py", line 253, in <module>
    initial_weights=initial_weights)
  File "./train.py", line 219, in train
    test_xs, test_ys = unzip(list(read_data("test/*.png"))[:50])
  File "./train.py", line 72, in unzip
    xs, ys = zip(*b)
ValueError: need more than 0 values to unpack

Thank's

**Comment by boyob** [comment]
read_data failed to get .png images and return null. Therefore *b=null and zip(*b) get zero argument.
