### ISSUE TITLE
Error While Running train.py

### ISSUE THREAD

**Issue by thug1705** [matthewearl/deep-anpr#49]
I am getting this error when I try to run train.py, any idea why ?? Thanks

Traceback (most recent call last):
  File "C:\Users\...\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\client\session.py", line 1039, in _do_call
    return fn(*args)
  File "C:\Users\...\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\client\session.py", line 1021, in _run_fn
    status, run_metadata)
  File "C:\Users\...\AppData\Local\Programs\Python\Python35\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Users\...\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 50 values, but the requested shape requires a multiple of 36
	 [[Node: Reshape_1 = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](strided_slice, Reshape_1/shape)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/.../PythonPyCharm/Tensorflow_Projects/Plate Recognition/deep-anpr-master/train.py", line 266, in <module>
    initial_weights=initial_weights)
  File "C:/Users/.../PythonPyCharm/Tensorflow_Projects/Plate Recognition/deep-anpr-master/train.py", line 239, in train
    do_batch()
  File "C:/Users/.../PythonPyCharm/Tensorflow_Projects/Plate Recognition/deep-anpr-master/train.py", line 222, in do_batch
    feed_dict={x: batch_xs, y_: batch_ys})
  File "C:\Users\...\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\client\session.py", line 778, in run
    run_metadata_ptr)
  File "C:\Users\...\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\client\session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "C:\Users\...\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\client\session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "C:\Users\...\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\client\session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 50 values, but the requested shape requires a multiple of 36
	 [[Node: Reshape_1 = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](strided_slice, Reshape_1/shape)]]

Caused by op 'Reshape_1', defined at:
  File "C:/Users/.../PythonPyCharm/Tensorflow_Projects/Plate Recognition/deep-anpr-master/train.py", line 266, in <module>
    initial_weights=initial_weights)
  File "C:/Users/.../PythonPyCharm/Tensorflow_Projects/Plate Recognition/deep-anpr-master/train.py", line 174, in train
    digits_loss, presence_loss, loss = get_loss(y, y_)
  File "C:/Users/.../PythonPyCharm/Tensorflow_Projects/Plate Recognition/deep-anpr-master/train.py", line 130, in get_loss
    [-1, len(common.CHARS)]),
  File "C:\Users\...\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\ops\gen_array_ops.py", line 2510, in reshape
    name=name)
  File "C:\Users\...\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\framework\op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "C:\Users\...\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\framework\ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Users\...\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\framework\ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Input to reshape is a tensor with 50 values, but the requested shape requires a multiple of 36
	 [[Node: Reshape_1 = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](strided_slice, Reshape_1/shape)]]

**Comment by thug1705** [comment]
I fixed, it was mistake in code made by me.

**Comment by engahmed1190** [comment]
Hi ,

I got this error also what is the cause of this error
