### ISSUE TITLE
Train problem

### ISSUE THREAD

**Issue by MansourTrabelsi** [matthewearl/deep-anpr#65]
`Traceback (most recent call last):
  File "train.py", line 258, in <module>
    initial_weights=initial_weights)
  File "train.py", line 224, in train
    test_xs, test_ys = unzip(list(read_data("test/*.png"))[:50])
  File "train.py", line 65, in read_data
    code = fname.split("/")[1][9:16]
IndexError: list index out of range`

How to fix this problem ?

**Comment by sauman07** [comment]
Any solution? Facing same issue.

**Comment by annalenastern** [comment]
if you are running it on windows theres no / in the path, so use fname.split("\\")[1][9:16]. works for me

**Comment by cayman1021** [comment]
Fixed this problem too by replacing the split character from "/" to "\\" (if you're in Windows).
