### ISSUE TITLE
train.py problem occure!!!help.help.help!!!

### ISSUE THREAD

**Issue by Mr-Yellow** [matthewearl/deep-anpr#75]
Traceback (most recent call last):
  File "train.py", line 293, in <module>
    initial_weights=initial_weights)
  File "train.py", line 266, in train
    do_batch()
  File "train.py", line 251, in do_batch
    do_report()
  File "train.py", line 236, in do_report
    print ("B{:3d} {:2.02f}% {:02.02f}% loss: {} "
AttributeError: 'NoneType' object has no attribute 'format'

**Comment by sauman07** [comment]
Any solution?

**Comment by chingjunehao** [comment]
Show me your code  after line 236, things that put .format

**Comment by IamSierraCharlie** [comment]
I ran into a similar issue - my brackets were wrong around the print statement.  I made the adjustment because I went from python 2.7 to 3.x
