### ISSUE TITLE
Meet the error where weights.npz cannot be passed into the detect.py

### ISSUE THREAD

**Issue by chingjunehao** [matthewearl/deep-anpr#84]
Traceback (most recent call last):
File "./detect.py", line 183, in 
f = np.loadtxt("weights.npz")
File "C:\Users\User\Anaconda3\envs\py35\lib\site-packages\numpy\lib\npyio.py", line 1024, in loadtxt
items = [conv(val) for (conv, val) in zip(converters, vals)]
File "C:\Users\User\Anaconda3\envs\py35\lib\site-packages\numpy\lib\npyio.py", line 1024, in 
items = [conv(val) for (conv, val) in zip(converters, vals)]
File "C:\Users\User\Anaconda3\envs\py35\lib\site-packages\numpy\lib\npyio.py", line 725, in floatconv
return float(x)
ValueError: could not convert string to float: b'PF\x05\x06\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

I'm running on Windows 10 using Anaconda with python 3.5
When I try to run 
`python ./detect.py in.jpg weights.npz out.jpg `
And the error occurs. Is there anyone met this problem?

**Comment by hengchuan** [comment]
ooo

**Comment by hengchuan** [comment]
ooo

**Comment by cayman1021** [comment]
Try using pip, not conda. Every package manager maintains its own different version. You can try the version obtained from pip.
