### ISSUE TITLE
train.py ERROR

### ISSUE THREAD

**Issue by C4A-yosy** [matthewearl/deep-anpr#89]
I can not execute train.py. Please help me!! m(_ _)m
Windows7, python3.5.4, tensorflow1.2.1, opencv3.3.1

AttributeError: Can't pickle local object 'mpgen.<locals>.main'   ...why???

*****
Traceback (most recent call last):
  File "train.py", line 269, in <module>
    initial_weights=initial_weights)
  File "train.py", line 241, in train
    for batch_idx, (batch_xs, batch_ys) in batch_iter:
  File "train.py", line 102, in wrapped
    proc.start()
  File "C:\ProgramData\Anaconda3\envs\svhn\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\ProgramData\Anaconda3\envs\svhn\lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\ProgramData\Anaconda3\envs\svhn\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "C:\ProgramData\Anaconda3\envs\svhn\lib\multiprocessing\popen_spawn_win32.py", line 66, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\ProgramData\Anaconda3\envs\svhn\lib\multiprocessing\reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'mpgen.<locals>.main'

(svhn) E:\yos\Tensorflow\svhn\deep-anpr-master>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\svhn\lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "C:\ProgramData\Anaconda3\envs\svhn\lib\multiprocessing\spawn.py", line 116, in _main
    self = pickle.load(from_parent)
EOFError: Ran out of input

**Comment by wenting521** [comment]
Does your problem have been solved? I also encountered the same problem and asked for answers. Thank you very much!

**Comment by crr0306** [comment]
Does your problem have been solved? I also encountered the same problem and asked for answers. Thank you very much!

**Comment by ZhimingHsu** [comment]
For me, win10 with python3.5

@mpgen => #@mpgen 
add # is work for my enviroment

**Comment by AsimSaif001** [comment]
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-11-2a562fccea06> in <module>()
    254 if __name__ == "__main__":
    255     if len(sys.argv) > 1:
--> 256         f = numpy.load(sys.argv[1])
    257         initial_weights = [f[n] for n in sorted(f.files,
    258                                                 key=lambda s: int(s[4:]))]

C:\Program Files\Anaconda3\envs\tensorflow\lib\site-packages\numpy\lib\npyio.py in load(file, mmap_mode, allow_pickle, fix_imports, encoding)
    370     own_fid = False
    371     if isinstance(file, basestring):
--> 372         fid = open(file, "rb")
    373         own_fid = True
    374     elif is_pathlib_path(file):

FileNotFoundError: [Errno 2] No such file or directory: '-f'

**Comment by AsimSaif001** [comment]
please help me
