### ISSUE TITLE
extractbgs.py error help!!

### ISSUE THREAD

**Issue by zn254937d** [matthewearl/deep-anpr#96]
Traceback (most recent call last):
  File "C:\deep-anpr-master\extractbgs.py", line 97, in <module>
    extract_backgrounds(sys.argv[1])
  File "C:\deep-anpr-master\extractbgs.py", line 62, in extract_backgrounds
    t = tarfile.open(name=archive_name)
  File "C:\Python27\lib\tarfile.py", line 1675, in open
    return func(name, "r", fileobj, **kwargs)
  File "C:\Python27\lib\tarfile.py", line 1740, in gzopen
    fileobj = gzip.GzipFile(name, mode, compresslevel, fileobj)
  File "C:\Python27\lib\gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: 'SUN397.tar.gz'

what should I do?
我該怎麼辦

**Comment by ZhimingHsu** [comment]
Do you have SUN397.tar.gz at extractbgs.py folder?
